version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "2777:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_network

volumes:
  mysql_data:

networks:
  spring_network:
